### ISSUE TITLE
Demo project "plot types" crashes when zoom out extremely

### ISSUE THREAD

**Issue by morningkyle** [swharden/ScottPlot#146]
Tested on master branch with demo project "plot types".

Test steps:
1. start up demo project "plot types"
2. Press button "clear"
3. Press button "Signal(10M points)"
4. Zoom out by mouse middle wheel until the the plot scaled to a point.

Expected behavior: demo app runs without crash.
Observed behavior: demo app crashes as below.

<img width="432" alt="PlotTypesDemoCrash" src="https://user-images.githubusercontent.com/31173219/66116816-f7e95600-e605-11e9-842a-c0b4d82b8793.PNG">

**Comment by morningkyle** [comment]
After some tracking, I found the crash(ArgumentOutOfRangeException) was due to overflows while calculating visibleIndex1/visibleIndex2 inside PlottableSignalConst::Render().  And PlottableSignal::Render() also has similar issue.

```
        public override void Render(Settings settings)
        {
            double dataSpanUnits = ys.Length * samplePeriod;
            double columnSpanUnits = settings.axes.x.span / settings.dataSize.Width;
            double columnPointCount = (columnSpanUnits / dataSpanUnits) * ys.Length;
            double offsetUnits = settings.axes.x.min - xOffset;
            double offsetPoints = offsetUnits / samplePeriod;
            int visibleIndex1 = (int)(offsetPoints);
            int visibleIndex2 = (int)(offsetPoints + columnPointCount * (settings.dataSize.Width + 1));
            int visiblePointCount = visibleIndex2 - visibleIndex1;
            ...
```

**Comment by swharden** [comment]
Hi @morningkyle thanks for reporting this one!

As you noted, this bug affected `PlottableSignal` and `PlottableSignalConst` objects. 

I think I fixed both with commit be43453. Let me know if you have any further issues!

**Comment by morningkyle** [comment]
Hi @swharden,
Thanks for the fix!  Yes, the crash is gone.   Just a note here, the overflow of visibleIndex1/2 still exist, but no visible side effect observed yet.
