### ISSUE TITLE
Create Layout() to interface the new layout system

### ISSUE THREAD

**Issue by citizen3942** [swharden/ScottPlot#156]
Whenever xAxis limits are set, for example, to 0 and 100, the tick labels are not visible. 0 and 100 should be visible, regardless.
They only appear after panning. In some cases, the panning is disabled, thus, it would e nice if these labels are visible.

**Comment by swharden** [comment]
Hi @citizen3942, I think I understand your issue. When you define axis limits, the two ticks at the edges do not get displayed.

```cs
int pointCount = 50;
double[] dataXs = ScottPlot.DataGen.Consecutive(pointCount);
double[] dataSin = ScottPlot.DataGen.Sin(pointCount);
formsPlot1.plt.PlotScatter(dataXs, dataSin);
formsPlot1.plt.Axis(x1: 0, x2: 100); // MANUALLY DEFINE HORIZONTAL AXIS LIMITS
formsPlot1.Render();
```

You would expect this code to display ticks at 0 and 100, but they appear off the screen. 

![image](https://user-images.githubusercontent.com/4165489/67167730-2b004900-f36b-11e9-8105-f2a421cb8a35.png)

Zooming out even a single pixel, they appear. I'll take a closer look!

**Comment by swharden** [comment]
I think it's fixed now!

```cs
formsPlot1.plt.Axis(x1: 0, x2: 50, y1: -1, y2: 1);
```

![image](https://user-images.githubusercontent.com/4165489/67167966-20df4a00-f36d-11e9-953d-370f3ca636eb.png)

**Comment by citizen3942** [comment]
The issue still remains in part. If one applies:
```cs
formsPlot1.plt.TightenLayout(padding: 0);
```
The tick labels are cut in half. Those must be shifted somehow, to fit the bounds of the plot canvas.
Here is an example at x1:
![image](https://user-images.githubusercontent.com/7060628/67236336-c10e9f00-f451-11e9-90da-7eb2a8ce31b7.png)

**Comment by swharden** [comment]
This seems like a very special case. 
It could be solved by some logic like:

```
all other horizontal tick labels are CenterAligned by default
if (no left padding) {make far left tick label LeftAligned}
if (no right padding) {set far right tick label RightAligned}
... and similar for vertical ticks
```

but I worry it would look ugly to have two ticks aligned differently than all the rest 🤔

**Comment by swharden** [comment]
Here are some mock-ups

### Normal Padding
![01](https://user-images.githubusercontent.com/4165489/67237130-a966f480-f418-11e9-84a5-2b079621148d.png)

### No left, right, or top padding
Now that the first and last ticks are shown (#154) they are partially when no padding is used
![02](https://user-images.githubusercontent.com/4165489/67237141-aec43f00-f418-11e9-9d8f-66536e9b9334.png)

### Suggested fix (first and last tick alignment)
I don't think this looks good 🤔 maybe a better solution would be to revert the change made in #154?
![03](https://user-images.githubusercontent.com/4165489/67237212-d3b8b200-f418-11e9-99e1-b0465c462c77.png)

**Comment by citizen3942** [comment]
In my opinion, it does not look bad at all and fulfills its purpose very well. 
In my case, I am trying to have an FFT synchronized with a spectrogram, and I prefer to have no padding on the left and right side of my plot. This allows me to utilize as many pixels as possible for spectrogram rendering.

PS! I am trying to figure out how to access Plottables and rendered FFT y values at their corresponding pixel position. Is there a way to do that?

**Comment by swharden** [comment]
> it fulfills its purpose very well

How would you feel if we simplified the logic and improved consistency by a rule like this?:

```
if (left padding is zero) { left-align all horizontal axis tick labels }
```

This would automatically knock-off the last label, and everything else would look consistent. We could do something similar for the vertical axis if the top padding is zero.

> In my case, I am trying to have an FFT synchronized with a spectrogram, and I prefer to have no padding on the left and right side of my plot. This allows me to utilize as many pixels as possible for spectrogram rendering.

Good to know! Whatever solution we come up with might be relevant to https://github.com/swharden/Spectrogram

> PS! I am trying to figure out how to access Plottables and rendered FFT y values at their corresponding pixel position. Is there a way to do that?

`plt.CoordinateFromPixel()` and `plt.CoordinateToPixel()`

**Comment by citizen3942** [comment]
> This would automatically knock-off the last label, and everything else would look consistent. We could do something similar for the vertical axis if the top padding is zero.
Could you make a mock-up for that? I think I follow, but how it would look?

**Comment by swharden** [comment]
> > This would automatically knock-off the last label, and everything else would look consistent. We could do something similar for the vertical axis if the top padding is zero.
> 
> Could you make a mock-up for that? I think I follow, but how it would look?

![image](https://user-images.githubusercontent.com/4165489/67240079-b71f7880-f41e-11e9-84ae-5fbba8942744.png)

**Comment by swharden** [comment]
We could also extend the tick length in this case if you want
![image](https://user-images.githubusercontent.com/4165489/67240252-14b3c500-f41f-11e9-8d78-4ef541bc65ab.png)

**Comment by citizen3942** [comment]
Perhaps those extended ticks and left-aligned labels are even acceptable.
The padding on the bottom should also be controlled somehow.
Maybe it would be a good idea to improve the plt.TightenLayout with leftPad, rightPad, topPad, and bottomPad parameters? What do you think?

**Comment by swharden** [comment]
> Perhaps those extended ticks and left-aligned labels are even acceptable.

If you want to hack this in now:
* change `settings.ticks.size` to `settings.ticks.size + 15` in the first line
* change `sfNorth` to `sfNorthWest` in the second line

https://github.com/swharden/ScottPlot/blob/cc5345742451da31a8fd2e8169f6f747931a5cbe/src/ScottPlot/Renderer.cs#L227-L228

I'll leave this ticket open to remind me to code-in this functionality more formally, and trigger it automatically when left padding is zero.

> The padding on the bottom should also be controlled somehow.
> Maybe it would be a good idea to improve the plt.TightenLayout with leftPad, rightPad, topPad, and bottomPad parameters? What do you think?

Yeah, revamping the whole layout system has been on my to-do list for a while! https://github.com/swharden/ScottPlot/issues/134

I anticipate getting to this within the next week or two.

**Comment by citizen3942** [comment]
> The padding on the bottom should also be controlled somehow.

A quick and "dirty" hack would be to this in Config/Layout.cs
```csharp
// bottom
int xLabelHeight = (int)gfx.MeasureString(xLabel.text, xLabel.font).Height;
paddingBySide[2] = Math.Max(xLabelHeight, tickLetterHeight);
//paddingBySide[2] += tickLetterHeight;
paddingBySide[2] += 5;
paddingBySide[2] += padOnAllSides;
```

**Comment by swharden** [comment]
I modified the code very similar to your suggestion. It automatically disables padding below ticks if the horizontal axis label is not used:

https://github.com/swharden/ScottPlot/blob/af376c129e014ad2eb4f2b3f8f447fd6a0931a11/src/ScottPlot/Config/Layout.cs#L38-L43

I decided to call the alternate tick styling _ruler mode_, and you can now turn it on with extra arguments in the `Tick()` function: 

https://github.com/swharden/ScottPlot/blob/1e84268bb95429ba1307f5d348fdf73d51170a4b/tests/ScottPlotTests/Recipes.cs#L449-L460

![image](https://user-images.githubusercontent.com/4165489/67248677-3028cb00-f433-11e9-8c30-57141fe65c43.png)

What do you think of these solutions?

**Comment by swharden** [comment]
I refactored the layout system - what a lot of work!

A simple way to do what you want is this:
https://github.com/swharden/ScottPlot/tree/master/cookbook#single-axis-with-no-padding

If you want to control everything, you can manually adjust all layout parameters:
https://github.com/swharden/ScottPlot/tree/master/cookbook#custom-padding
